altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  eb91905f-5ef8-41d0-bd16-a872cf3f0aad:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-20T20:44:08+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: c87ea603-e6d8-44b8-98ab-f965d5870baf
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a39d543d-ec85-4505-8522-728cae075214
        userCondition: null
fs: assets
handle: assets
name: Assets
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
