dateModified: 1742494784
email:
  fromEmail: kaitlynmclaughlin25@gmail.com
  fromName: 'craft sample'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    823c0cd6-eceb-4804-b6a6-f19cc87cb031: 'craft sample' # craft sample
    a309fa3b-3cc4-46b2-b049-93d6bdd8f2ef: 'craft sample' # craft sample
    d60822b8-c721-4180-ae0c-69d8988a0112: 'Public Schema' # Public Schema
system:
  edition: solo
  live: true
  name: 'craft sample'
  schemaVersion: 5.6.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
