dateModified: 1742511830
email:
  fromEmail: kaitlynmclaughlin25@gmail.com
  fromName: 'craft sample'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  assets:
    hasUrls: true
    name: assets
    settings:
      path: '@webroot/assets'
    type: craft\fs\Local
    url: '@web/assets/'
meta:
  __names__:
    0c1e2a5d-15c2-45d0-a5a8-33bd4be8dc01: Home # Home
    5d703863-88c5-40a3-b0be-7b51b4613fa5: Assets # Assets
    9d5c89fd-a525-429b-bf1e-5475ac03f849: Home # Home
    30eb955e-d3a3-4e00-8459-d3bd058a535c: Image # Image
    38f33cf9-0f11-462c-a659-18410eebd4d2: 'Content Block' # Content Block
    44bd5a8c-a5f7-46ef-ae47-ffb9e66bed06: 'Images Section' # Images Section
    583d6df1-bebe-4877-bc55-14afda33f77f: 'Homepage Categories' # Homepage Categories
    823c0cd6-eceb-4804-b6a6-f19cc87cb031: 'craft sample' # craft sample
    a1e1aad6-b9d8-4afc-a9ef-2e5bd08bd989: 'Category Block' # Category Block
    a309fa3b-3cc4-46b2-b049-93d6bdd8f2ef: 'craft sample' # craft sample
    bb9a066d-9eb8-4058-9139-dff9e5308f67: 'Homepage Categories' # Homepage Categories
    bcd24fdf-377e-4a6d-869c-4a5a5f2676a1: Header # Header
    d60822b8-c721-4180-ae0c-69d8988a0112: 'Public Schema' # Public Schema
system:
  edition: solo
  live: true
  name: 'craft sample'
  schemaVersion: 5.6.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
